enum ActionTypes {
  SEARCH_USERS = 'SEARCH_USERS',
  GET_USER = 'GET_USER',
  GET_USERS_PENDING = 'GET_USERS_PENDING',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS ',
  GET_USERS_FAILURE = 'GET_USERS_FAILURE',
  SEARCH_REPOS = 'SEARCH_REPOS',
  GET_REPO = 'GET_REPO',
  GET_REPOS_PENDING = 'GET_REPOS_PENDING',
  GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS ',
  GET_REPOS_FAILURE = 'GET_REPOS_FAILURE',
}

export default ActionTypes
